Add PIP22 regression tests
pokt-network/pocket-core-func-tests pull request #40
Opened 2022-07-11 11:25 UTC by Andrew-Pohl

Wasn't entirely sure how the scenario number was done so have left these blank for now.

2022-07-11 11:26 UTC, Andrew-Pohl commented
@luyzdeleon FYI I can't add reviewers

2022-07-18 19:46 UTC, luyzdeleon requested changes
I believe before looking at the test themselves we should group scenarios in the following categories:

1. Before the upgrade height (the one that tells validators to be running on RC-0.9.0)
2. After the upgrade height.
2.a. After RSCAL is activated
2.b. After VEDIT is activated
3.c. When RSCAL and VEDIT are not active at the same time.

2022-07-26 19:50 UTC, luyzdeleon requested changes

2022-07-26 19:50 UTC, luyzdeleon commented on tests/PIP-22/behavioral-tests.feature
> +Scenario: xxx Make sure stake can be updated friely within the same bin when VEDIT is disabled and RSCAL is diabled
Typo here: `friely`, should be `freely`

2022-07-26 19:50 UTC, luyzdeleon commented on tests/PIP-22/behavioral-tests.feature
> +Scenario: xxx Make sure stake can be updated friely within the same bin when VEDIT is disabled and RSCAL is enabled
Typo here: `friely`, should be `freely`

2022-07-26 19:50 UTC, luyzdeleon commented on tests/PIP-22/behavioral-tests.feature
> +Scenario: xxx Make sure stake can be updated friely within the same bin when VEDIT is enabled and RSCAL is disabled
Typo here: `friely`, should be `freely`

2022-07-26 19:50 UTC, luyzdeleon commented on tests/PIP-22/behavioral-tests.feature
> +Scenario: xxx Make sure stake can not be updated friely within the same bin when VEDIT and RSCAL is enabled
Typo here: `friely`, should be `freely`

2022-07-26 19:50 UTC, luyzdeleon commented on tests/PIP-22/behavioral-tests.feature
> +Scenario: xxx Make sure stake can be updated friely to the next bin when VEDIT and RSCAL is enabled
Typo here: `friely`, should be `freely`

2022-07-26 20:54 UTC, Andrew-Pohl commented on tests/PIP-22/behavioral-tests.feature
> +Scenario: xxx Make sure stake can be updated friely within the same bin when VEDIT is disabled and RSCAL is diabled
Whoops, copy and paste of a typo there. Fixed in [7b2ac1a](https://github.com/pokt-network/pocket-core-func-tests/pull/40/commits/7b2ac1abe8696c633960501368f60ee0fc244d0f)

2022-07-27 14:17 UTC, luyzdeleon approved these changes

2022-08-11 18:21 UTC, merged

2022-08-25 18:38 UTC, emedrano2112 reviewed
Proposed scenarios LGTM.

As mentioned in different threads, these are missing the Execution evidence as agreed on the contribution guide process, Success Criteria section. We agreed to proceed as is due to the tight timeline existing for this release, please provide when possible.